---
title: "dw_II_class_2"
author: "Caleigh Dwyer"
date: "2023-10-17"
output: github_document
---


```{r}
library(rvest)
library(tidyverse)
library(p8105.datasets)
```


##strings

```{r}
string_vec = c("my", "name", "is", "jeff")

str_detect(string_vec, "e")
##when you run the above, it tells you which of the values match your condition! You can use along with filter to find observations you want to get rid of


str(replace(string_vec, "jeff", "Jeff G"))
```



```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
)

str_detect(string_vec, "i think")
##above just finds any case that matches the words, whereas one below finds any case that starts with the match
str_detect(string_vec, "^i think")
##below finds the one where i think is in the end
str_detect(string_vec, "i think$")
```


```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
)

str_detect(string_vec, "[Pp]umpkin")

##above finds both upper and lower case matches
```


```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss',
  'she is 5 feet 4 in tall',
  '3am - cant sleep :('
)

str_detect(string_vec, "[0-9]")
str_detect(string_vec, "^[0-9]")
str_detect(string_vec, "^[0-9][a-z]")
## you can combine conditions
```


```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 2023.'
)

str_detect(string_vec,"7.11")
##above finds any 7 11 phrase with character inbetween
```


```{r}
string_vec = c(
  "[sfdjkls]",
  ":]",
  ":[",
  "I found [6-7]"
)
str_detect(string_vec, "\\[")
str_detect(string_vec, "\\[[0-9]")

##to find a special character, you have to use brackets to indicate what you're looking for, because otherwise str detect will interpret it functionally
##this is why people dont want you using special characters, because it's hard to detect
```

##factors

```{r}
vec_sex = c("male", "male", "female", "female")
vec_sex = factor(c("male", "male", "female", "female"))
vec_sex

##notice differences when you run the two above. when a factor, values are no longer in "" and it indicates levels
as.numeric(vec_sex)

vec_sex = fct_relevel(vec_sex, "male")
vec_sex

as.numeric(vec_sex)

##use fct_relevel to reorder factors


```


##NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

table_marj =
  read_html(nsduh_url) |> 
  html_table() |> 
  first() |> 
  slice(-1)
```

need to tidy this

```{r}
marj_df =
  table_marj |> 
  select(-contains ("P Value")) |> 
  pivot_longer(
    -State,
    names_to = "age_year",
    values_to = "percent"
  ) |> 
  separate(age_year, into = c("age", "year"), "\\(") |> 
  mutate(year = str_replace(year, "\\)", ""),
percent = str_replace(percent, "[a-b]", ""),
percent = as.numeric(percent)) |> 
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))


##pivot longer because age and year were a column name
##now need to seaparate age and year
```


```{r}
marj_df |> 
  filter(age == "18-25") |> 
  mutate(State = fct_reorder(State, percent)) |> 
  ggplot(aes(x = State, y = percent, color = year))+
  geom_point()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```


##NYC restuarant inspections

```{r}
rest_inspec |> view()

rest_inspec |> 
  count(boro, grade) |> 
  pivot_wider(
    names_from = grade,
    values_from = n) |> 
  knitr:kable()


inspection_df =
  rest_inspec |> 
  filter(grade %in% c("A", "B", "C"), boro != "Missing") |> 
  mutate(boro = str_to_title(boro),
         dba = str_to_upper(dba))

```

pizza

```{r}
inspection_df |> 
  filter(str_detect(dba, "PIZZA")) |> 
  mutate(boro = fct_infreq(boro)) |> 
  ggplot(aes(x = boro, fill= grade))+
geom_bar()

##fct_infreq orders boro by count
```



```{r}
inspection_df |> 
  filter(str_detect(dba, "PIZZA")) |> 
  mutate(boro = fct_infreq(boro),
         boro = str_replace(boro, "Manhattan", "The City")) |> 
  ggplot(aes(x = boro, fill= grade))+
geom_bar()

##order matters for mutate. if you're going to reorder w/ factor, you need to do it after you've cleaned up names of variables


inspection_df |> 
  filter(str_detect(dba, "PIZZA")) |> 
  mutate(boro = fct_infreq(boro),
         boro = fct_recode(boro, "The City" = "Manhattan")) |> 
  ggplot(aes(x = boro, fill= grade))+
geom_bar()
```


with regression, use factors to tell R which is the reference categorize

